version: "3.7"

services:
  neo:
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
